// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwzgZPPJcmgKKvM7MozUW8yYx68CEghFM',
    appId: '1:131809460710:web:dfe2f9fac2a275e218d627',
    messagingSenderId: '131809460710',
    projectId: 'soda-firebase',
    authDomain: 'soda-firebase.firebaseapp.com',
    storageBucket: 'soda-firebase.appspot.com',
    measurementId: 'G-J6TJ4RNJP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDywCB3_HfnvUFLedHaQiYhJg-9ctsjeK0',
    appId: '1:131809460710:android:973ad3b5b9f0f0e218d627',
    messagingSenderId: '131809460710',
    projectId: 'soda-firebase',
    storageBucket: 'soda-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKwmH1-vBYIE1eHbUMoesB75BJLEkHLms',
    appId: '1:131809460710:ios:499a7ab73883422a18d627',
    messagingSenderId: '131809460710',
    projectId: 'soda-firebase',
    storageBucket: 'soda-firebase.appspot.com',
    iosClientId: '131809460710-b0tp6fdn3ea884jpararfs385t523bnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.welcomeToSoda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKwmH1-vBYIE1eHbUMoesB75BJLEkHLms',
    appId: '1:131809460710:ios:499a7ab73883422a18d627',
    messagingSenderId: '131809460710',
    projectId: 'soda-firebase',
    storageBucket: 'soda-firebase.appspot.com',
    iosClientId: '131809460710-b0tp6fdn3ea884jpararfs385t523bnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.welcomeToSoda',
  );
}
